//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawReceiver) DeepCopyInto(out *RawReceiver) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawReceiver.
func (in *RawReceiver) DeepCopy() *RawReceiver {
	if in == nil {
		return nil
	}
	out := new(RawReceiver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnoopyDataEndpoint) DeepCopyInto(out *SnoopyDataEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnoopyDataEndpoint.
func (in *SnoopyDataEndpoint) DeepCopy() *SnoopyDataEndpoint {
	if in == nil {
		return nil
	}
	out := new(SnoopyDataEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnoopyDataEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnoopyDataEndpointList) DeepCopyInto(out *SnoopyDataEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SnoopyDataEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnoopyDataEndpointList.
func (in *SnoopyDataEndpointList) DeepCopy() *SnoopyDataEndpointList {
	if in == nil {
		return nil
	}
	out := new(SnoopyDataEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnoopyDataEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnoopyDataEndpointSpec) DeepCopyInto(out *SnoopyDataEndpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnoopyDataEndpointSpec.
func (in *SnoopyDataEndpointSpec) DeepCopy() *SnoopyDataEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(SnoopyDataEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnoopyDataEndpointStatus) DeepCopyInto(out *SnoopyDataEndpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnoopyDataEndpointStatus.
func (in *SnoopyDataEndpointStatus) DeepCopy() *SnoopyDataEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(SnoopyDataEndpointStatus)
	in.DeepCopyInto(out)
	return out
}
